### ISSUE TITLE
I made a Nim binding for picohttpparser

### ISSUE THREAD

**Issue by philip-wernersbach** [h2o/picohttpparser#23]
I made a Nim binding for picohttpparser. Do you want me to submit a pull request for it, or make it a separate repository?

**Comment by philip-wernersbach** [comment]
My opinion is that it's better to have it in this repository.

**Comment by kazuho** [comment]
Thank you for the ping.

I'd suggest maintaining it as a separate project, since the lifetime of the two might be different. A number of bindings already exist for various programming languages, all are maintained separately.

That said, it might be a good idea to create a list of softwares that make use of picohttpparser.

**Comment by philip-wernersbach** [comment]
Fair enough. I've uploaded the Nim binding to https://github.com/philip-wernersbach/nim-picohttpparser. Thanks for making this awesome library!
