### ISSUE TITLE
Why not hand written Boyer-Moore in is_complete?

### ISSUE THREAD

**Issue by vinniefalco** [h2o/picohttpparser#37]
I was surprised to see `is_complete` operates on a character at a time, why not this:
```
char const*
find_eom(char const* p, char const* last)
{
    for(;;)
    {
        if(p + 4 > last)
            return nullptr;
        if(p[3] != '\n')
        {
            if(p[3] == '\r')
                ++p;
            else
                p += 4;
        }
        else if(p[2] != '\r')
        {
            p += 4;
        }
        else if(p[1] != '\n')
        {
            p += 2;
        }
        else if(p[0] != '\r')
        {
            p += 2;
        }
        else
        {
            return p + 4;
        }
    }
}
```

**Comment by kazuho** [comment]
We could do that. The reason it has not been done is because it is not a hot path.

In almost all cases, a HTTP client will send the entire request at once. The moment that `is_complete` is called is when a client sends either a HTTP reqquest with a very long header or does a Slowloris attack.

In either case, other parts (e.g. syscall or `parse_headers`) will take more time than looking for `\r?\n\r?\n`.

**Comment by vinniefalco** [comment]
Yes, I see now, thanks for explaining it. I was under the impression that the parser didn't do anything until it detected the final `\r\n\r\n` sequence (i.e. `is_complete`). I did not realize that `is_complete` is only called after the parse fails to find the end of the message once (is my understanding correct?)
